# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "C:\Users\ndoum\prog6221-part-2-ST10281928-Ndivhuwo-Ndou\ST10281928-NDIVHUWO NDOU-PROG6221-PART2\ST10281928-NDIVHUWO NDOU-PROG6221-PART2.csproj"
    - name: Build
      run: dotnet build "C:\Users\ndoum\prog6221-part-2-ST10281928-Ndivhuwo-Ndou\ST10281928-NDIVHUWO NDOU-PROG6221-PART2\ST10281928-NDIVHUWO NDOU-PROG6221-PART2.csproj" --no-restore
    - name: Test
      run: dotnet test  "C:\Users\ndoum\prog6221-part-2-ST10281928-Ndivhuwo-Ndou\ST10281928-NDIVHUWO NDOU-PROG6221-PART2\ST10281928-NDIVHUWO NDOU-PROG6221-PART2.csproj"--no-build --verbosity normal
